/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pong_gpio_Gpio */

#ifndef _Included_pong_gpio_Gpio
#define _Included_pong_gpio_Gpio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pong_gpio_Gpio
 * Method:    listen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pong_gpio_Gpio_listen
  (JNIEnv *, jobject);

/*
 * Class:     pong_gpio_Gpio
 * Method:    send
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_pong_gpio_Gpio_send
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
